// Code generated by protoc-gen-go. DO NOT EDIT.
// source: global_def.proto

package fsapi

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrCode int32

const (
	ErrCode_ERR_SUCCESS              ErrCode = 0
	ErrCode_ERR_FAILED               ErrCode = 1
	ErrCode_ERR_DEVID_NOT_EXIST      ErrCode = 2
	ErrCode_ERR_CONN_TO_DA_NOT_READY ErrCode = 3
)

var ErrCode_name = map[int32]string{
	0: "ERR_SUCCESS",
	1: "ERR_FAILED",
	2: "ERR_DEVID_NOT_EXIST",
	3: "ERR_CONN_TO_DA_NOT_READY",
}

var ErrCode_value = map[string]int32{
	"ERR_SUCCESS":              0,
	"ERR_FAILED":               1,
	"ERR_DEVID_NOT_EXIST":      2,
	"ERR_CONN_TO_DA_NOT_READY": 3,
}

func (x ErrCode) String() string {
	return proto.EnumName(ErrCode_name, int32(x))
}

func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_24a8c9fe6e60032d, []int{0}
}

type ReqHeader struct {
	// 现在版本默认为 1
	Version int32 `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	// 设备ID
	DevId string `protobuf:"bytes,2,opt,name=DevId,proto3" json:"DevId,omitempty"`
	//时间戳 unix_timestamp
	Ts                   uint32   `protobuf:"varint,3,opt,name=Ts,proto3" json:"Ts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqHeader) Reset()         { *m = ReqHeader{} }
func (m *ReqHeader) String() string { return proto.CompactTextString(m) }
func (*ReqHeader) ProtoMessage()    {}
func (*ReqHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_24a8c9fe6e60032d, []int{0}
}

func (m *ReqHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqHeader.Unmarshal(m, b)
}
func (m *ReqHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqHeader.Marshal(b, m, deterministic)
}
func (m *ReqHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqHeader.Merge(m, src)
}
func (m *ReqHeader) XXX_Size() int {
	return xxx_messageInfo_ReqHeader.Size(m)
}
func (m *ReqHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ReqHeader proto.InternalMessageInfo

func (m *ReqHeader) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ReqHeader) GetDevId() string {
	if m != nil {
		return m.DevId
	}
	return ""
}

func (m *ReqHeader) GetTs() uint32 {
	if m != nil {
		return m.Ts
	}
	return 0
}

type ResHeader struct {
	// 现在版本默认为 1
	Version              int32    `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	ErrCode              ErrCode  `protobuf:"varint,2,opt,name=ErrCode,proto3,enum=fsapi.ErrCode" json:"ErrCode,omitempty"`
	ErrMsg               string   `protobuf:"bytes,3,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	ReqId                string   `protobuf:"bytes,4,opt,name=ReqId,proto3" json:"ReqId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResHeader) Reset()         { *m = ResHeader{} }
func (m *ResHeader) String() string { return proto.CompactTextString(m) }
func (*ResHeader) ProtoMessage()    {}
func (*ResHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_24a8c9fe6e60032d, []int{1}
}

func (m *ResHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResHeader.Unmarshal(m, b)
}
func (m *ResHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResHeader.Marshal(b, m, deterministic)
}
func (m *ResHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResHeader.Merge(m, src)
}
func (m *ResHeader) XXX_Size() int {
	return xxx_messageInfo_ResHeader.Size(m)
}
func (m *ResHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ResHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ResHeader proto.InternalMessageInfo

func (m *ResHeader) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ResHeader) GetErrCode() ErrCode {
	if m != nil {
		return m.ErrCode
	}
	return ErrCode_ERR_SUCCESS
}

func (m *ResHeader) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *ResHeader) GetReqId() string {
	if m != nil {
		return m.ReqId
	}
	return ""
}

func init() {
	proto.RegisterEnum("fsapi.ErrCode", ErrCode_name, ErrCode_value)
	proto.RegisterType((*ReqHeader)(nil), "fsapi.ReqHeader")
	proto.RegisterType((*ResHeader)(nil), "fsapi.ResHeader")
}

func init() { proto.RegisterFile("global_def.proto", fileDescriptor_24a8c9fe6e60032d) }

var fileDescriptor_24a8c9fe6e60032d = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcf, 0x6f, 0xa2, 0x40,
	0x1c, 0xc5, 0x17, 0x5c, 0x35, 0xce, 0x66, 0x59, 0x32, 0xdb, 0xb4, 0x1c, 0x7a, 0x30, 0x9e, 0x48,
	0x93, 0x0e, 0x49, 0x7b, 0xe8, 0x59, 0x61, 0x54, 0x52, 0xab, 0xcd, 0x40, 0xed, 0x8f, 0x0b, 0xc1,
	0xe1, 0x0b, 0x25, 0x41, 0x07, 0x07, 0x6c, 0x4f, 0xfd, 0x67, 0xfa, 0x97, 0x36, 0x8c, 0xda, 0x6b,
	0x8f, 0x9f, 0xf7, 0xf2, 0xde, 0xbc, 0xcc, 0x17, 0x99, 0x59, 0x21, 0x56, 0x71, 0x11, 0x25, 0x90,
	0x92, 0x52, 0x8a, 0x5a, 0xe0, 0x76, 0x5a, 0xc5, 0x65, 0x3e, 0xb8, 0x45, 0x3d, 0x06, 0xdb, 0x29,
	0xc4, 0x09, 0x48, 0x6c, 0xa1, 0xee, 0x12, 0x64, 0x95, 0x8b, 0x8d, 0xa5, 0xf5, 0x35, 0xbb, 0xcd,
	0x8e, 0x88, 0x4f, 0x50, 0xdb, 0x83, 0x37, 0x3f, 0xb1, 0xf4, 0xbe, 0x66, 0xf7, 0xd8, 0x1e, 0xb0,
	0x81, 0xf4, 0xb0, 0xb2, 0x5a, 0x7d, 0xcd, 0xfe, 0xcb, 0xf4, 0xb0, 0x1a, 0x7c, 0x34, 0x65, 0xd5,
	0x8f, 0x65, 0x36, 0xea, 0x52, 0x29, 0x5d, 0x91, 0x80, 0xaa, 0x33, 0xae, 0x0c, 0xa2, 0xc6, 0x90,
	0x83, 0xca, 0x8e, 0x36, 0x3e, 0x45, 0x1d, 0x2a, 0xe5, 0x5d, 0x95, 0xa9, 0x47, 0x7a, 0xec, 0x40,
	0xcd, 0x1c, 0x06, 0x5b, 0x3f, 0xb1, 0x7e, 0xef, 0xe7, 0x28, 0xb8, 0x88, 0xbf, 0x7b, 0xf1, 0x3f,
	0xf4, 0x87, 0x32, 0x16, 0x05, 0x0f, 0xae, 0x4b, 0x83, 0xc0, 0xfc, 0x85, 0x0d, 0x84, 0x1a, 0x61,
	0x3c, 0xf4, 0x67, 0xd4, 0x33, 0x35, 0x7c, 0x86, 0xfe, 0x37, 0xec, 0xd1, 0xa5, 0xef, 0x45, 0xf3,
	0x45, 0x18, 0xd1, 0x27, 0x3f, 0x08, 0x4d, 0x1d, 0x9f, 0x23, 0xab, 0x31, 0xdc, 0xc5, 0x7c, 0x1e,
	0x85, 0x8b, 0xc8, 0x1b, 0x2a, 0x97, 0xd1, 0xa1, 0xf7, 0x6c, 0xb6, 0x46, 0x6b, 0x64, 0xf1, 0x0d,
	0xc9, 0x45, 0x99, 0x67, 0x24, 0x05, 0x48, 0x48, 0xc5, 0xe3, 0x02, 0x48, 0x26, 0x4b, 0x3e, 0x32,
	0xc7, 0x00, 0x49, 0xc0, 0xe3, 0x82, 0xc3, 0x44, 0x96, 0x7c, 0xf2, 0x7e, 0xaf, 0xbd, 0xdc, 0x64,
	0x79, 0xfd, 0xba, 0x5b, 0x11, 0x2e, 0xd6, 0x8e, 0x4a, 0x39, 0x4d, 0xea, 0x52, 0xa5, 0x9c, 0x7c,
	0x53, 0x83, 0x4c, 0x63, 0x0e, 0x4e, 0x93, 0x77, 0x32, 0x11, 0x89, 0x5d, 0xed, 0xa8, 0xaf, 0xf8,
	0xd4, 0x5b, 0xd3, 0xd9, 0xe3, 0xaa, 0xa3, 0x6e, 0x75, 0xfd, 0x15, 0x00, 0x00, 0xff, 0xff, 0x42,
	0x46, 0x93, 0xc4, 0xbf, 0x01, 0x00, 0x00,
}
