// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: global_def.proto

package fsapi;

public final class GlobalDef {
  private GlobalDef() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code fsapi.ErrCode}
   */
  public enum ErrCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *0 成功
     * </pre>
     *
     * <code>ERR_SUCCESS = 0;</code>
     */
    ERR_SUCCESS(0),
    /**
     * <pre>
     *1 失败
     * </pre>
     *
     * <code>ERR_FAILED = 1;</code>
     */
    ERR_FAILED(1),
    /**
     * <pre>
     *2 地址已经存在
     * </pre>
     *
     * <code>ERR_DEVID_NOT_EXIST = 2;</code>
     */
    ERR_DEVID_NOT_EXIST(2),
    /**
     * <pre>
     *3 连接没有准备好
     * </pre>
     *
     * <code>ERR_CONN_TO_DA_NOT_READY = 3;</code>
     */
    ERR_CONN_TO_DA_NOT_READY(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *0 成功
     * </pre>
     *
     * <code>ERR_SUCCESS = 0;</code>
     */
    public static final int ERR_SUCCESS_VALUE = 0;
    /**
     * <pre>
     *1 失败
     * </pre>
     *
     * <code>ERR_FAILED = 1;</code>
     */
    public static final int ERR_FAILED_VALUE = 1;
    /**
     * <pre>
     *2 地址已经存在
     * </pre>
     *
     * <code>ERR_DEVID_NOT_EXIST = 2;</code>
     */
    public static final int ERR_DEVID_NOT_EXIST_VALUE = 2;
    /**
     * <pre>
     *3 连接没有准备好
     * </pre>
     *
     * <code>ERR_CONN_TO_DA_NOT_READY = 3;</code>
     */
    public static final int ERR_CONN_TO_DA_NOT_READY_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ErrCode valueOf(int value) {
      return forNumber(value);
    }

    public static ErrCode forNumber(int value) {
      switch (value) {
        case 0: return ERR_SUCCESS;
        case 1: return ERR_FAILED;
        case 2: return ERR_DEVID_NOT_EXIST;
        case 3: return ERR_CONN_TO_DA_NOT_READY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ErrCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrCode>() {
            public ErrCode findValueByNumber(int number) {
              return ErrCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return fsapi.GlobalDef.getDescriptor().getEnumTypes().get(0);
    }

    private static final ErrCode[] VALUES = values();

    public static ErrCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ErrCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:fsapi.ErrCode)
  }

  public interface ReqHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:fsapi.ReqHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 现在版本默认为 1
     * </pre>
     *
     * <code>int32 Version = 1;</code>
     */
    int getVersion();

    /**
     * <pre>
     * 设备ID
     * </pre>
     *
     * <code>string DevId = 2;</code>
     */
    java.lang.String getDevId();
    /**
     * <pre>
     * 设备ID
     * </pre>
     *
     * <code>string DevId = 2;</code>
     */
    com.google.protobuf.ByteString
        getDevIdBytes();

    /**
     * <pre>
     *时间戳 unix_timestamp
     * </pre>
     *
     * <code>uint32 Ts = 3;</code>
     */
    int getTs();
  }
  /**
   * Protobuf type {@code fsapi.ReqHeader}
   */
  public  static final class ReqHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:fsapi.ReqHeader)
      ReqHeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReqHeader.newBuilder() to construct.
    private ReqHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReqHeader() {
      devId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReqHeader();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReqHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              version_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              devId_ = s;
              break;
            }
            case 24: {

              ts_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fsapi.GlobalDef.internal_static_fsapi_ReqHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fsapi.GlobalDef.internal_static_fsapi_ReqHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fsapi.GlobalDef.ReqHeader.class, fsapi.GlobalDef.ReqHeader.Builder.class);
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <pre>
     * 现在版本默认为 1
     * </pre>
     *
     * <code>int32 Version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int DEVID_FIELD_NUMBER = 2;
    private volatile java.lang.Object devId_;
    /**
     * <pre>
     * 设备ID
     * </pre>
     *
     * <code>string DevId = 2;</code>
     */
    public java.lang.String getDevId() {
      java.lang.Object ref = devId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        devId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 设备ID
     * </pre>
     *
     * <code>string DevId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDevIdBytes() {
      java.lang.Object ref = devId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        devId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TS_FIELD_NUMBER = 3;
    private int ts_;
    /**
     * <pre>
     *时间戳 unix_timestamp
     * </pre>
     *
     * <code>uint32 Ts = 3;</code>
     */
    public int getTs() {
      return ts_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (version_ != 0) {
        output.writeInt32(1, version_);
      }
      if (!getDevIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, devId_);
      }
      if (ts_ != 0) {
        output.writeUInt32(3, ts_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (!getDevIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, devId_);
      }
      if (ts_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, ts_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof fsapi.GlobalDef.ReqHeader)) {
        return super.equals(obj);
      }
      fsapi.GlobalDef.ReqHeader other = (fsapi.GlobalDef.ReqHeader) obj;

      if (getVersion()
          != other.getVersion()) return false;
      if (!getDevId()
          .equals(other.getDevId())) return false;
      if (getTs()
          != other.getTs()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + DEVID_FIELD_NUMBER;
      hash = (53 * hash) + getDevId().hashCode();
      hash = (37 * hash) + TS_FIELD_NUMBER;
      hash = (53 * hash) + getTs();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static fsapi.GlobalDef.ReqHeader parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fsapi.GlobalDef.ReqHeader parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fsapi.GlobalDef.ReqHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fsapi.GlobalDef.ReqHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fsapi.GlobalDef.ReqHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fsapi.GlobalDef.ReqHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fsapi.GlobalDef.ReqHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fsapi.GlobalDef.ReqHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static fsapi.GlobalDef.ReqHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static fsapi.GlobalDef.ReqHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static fsapi.GlobalDef.ReqHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fsapi.GlobalDef.ReqHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fsapi.GlobalDef.ReqHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fsapi.ReqHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fsapi.ReqHeader)
        fsapi.GlobalDef.ReqHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fsapi.GlobalDef.internal_static_fsapi_ReqHeader_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fsapi.GlobalDef.internal_static_fsapi_ReqHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fsapi.GlobalDef.ReqHeader.class, fsapi.GlobalDef.ReqHeader.Builder.class);
      }

      // Construct using fsapi.GlobalDef.ReqHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = 0;

        devId_ = "";

        ts_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fsapi.GlobalDef.internal_static_fsapi_ReqHeader_descriptor;
      }

      @java.lang.Override
      public fsapi.GlobalDef.ReqHeader getDefaultInstanceForType() {
        return fsapi.GlobalDef.ReqHeader.getDefaultInstance();
      }

      @java.lang.Override
      public fsapi.GlobalDef.ReqHeader build() {
        fsapi.GlobalDef.ReqHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public fsapi.GlobalDef.ReqHeader buildPartial() {
        fsapi.GlobalDef.ReqHeader result = new fsapi.GlobalDef.ReqHeader(this);
        result.version_ = version_;
        result.devId_ = devId_;
        result.ts_ = ts_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fsapi.GlobalDef.ReqHeader) {
          return mergeFrom((fsapi.GlobalDef.ReqHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fsapi.GlobalDef.ReqHeader other) {
        if (other == fsapi.GlobalDef.ReqHeader.getDefaultInstance()) return this;
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (!other.getDevId().isEmpty()) {
          devId_ = other.devId_;
          onChanged();
        }
        if (other.getTs() != 0) {
          setTs(other.getTs());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fsapi.GlobalDef.ReqHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fsapi.GlobalDef.ReqHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int version_ ;
      /**
       * <pre>
       * 现在版本默认为 1
       * </pre>
       *
       * <code>int32 Version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <pre>
       * 现在版本默认为 1
       * </pre>
       *
       * <code>int32 Version = 1;</code>
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 现在版本默认为 1
       * </pre>
       *
       * <code>int32 Version = 1;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object devId_ = "";
      /**
       * <pre>
       * 设备ID
       * </pre>
       *
       * <code>string DevId = 2;</code>
       */
      public java.lang.String getDevId() {
        java.lang.Object ref = devId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          devId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 设备ID
       * </pre>
       *
       * <code>string DevId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDevIdBytes() {
        java.lang.Object ref = devId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          devId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 设备ID
       * </pre>
       *
       * <code>string DevId = 2;</code>
       */
      public Builder setDevId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        devId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 设备ID
       * </pre>
       *
       * <code>string DevId = 2;</code>
       */
      public Builder clearDevId() {
        
        devId_ = getDefaultInstance().getDevId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 设备ID
       * </pre>
       *
       * <code>string DevId = 2;</code>
       */
      public Builder setDevIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        devId_ = value;
        onChanged();
        return this;
      }

      private int ts_ ;
      /**
       * <pre>
       *时间戳 unix_timestamp
       * </pre>
       *
       * <code>uint32 Ts = 3;</code>
       */
      public int getTs() {
        return ts_;
      }
      /**
       * <pre>
       *时间戳 unix_timestamp
       * </pre>
       *
       * <code>uint32 Ts = 3;</code>
       */
      public Builder setTs(int value) {
        
        ts_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间戳 unix_timestamp
       * </pre>
       *
       * <code>uint32 Ts = 3;</code>
       */
      public Builder clearTs() {
        
        ts_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:fsapi.ReqHeader)
    }

    // @@protoc_insertion_point(class_scope:fsapi.ReqHeader)
    private static final fsapi.GlobalDef.ReqHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new fsapi.GlobalDef.ReqHeader();
    }

    public static fsapi.GlobalDef.ReqHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReqHeader>
        PARSER = new com.google.protobuf.AbstractParser<ReqHeader>() {
      @java.lang.Override
      public ReqHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReqHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReqHeader> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public fsapi.GlobalDef.ReqHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:fsapi.ResHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 现在版本默认为 1
     * </pre>
     *
     * <code>int32 Version = 1;</code>
     */
    int getVersion();

    /**
     * <code>.fsapi.ErrCode ErrCode = 2;</code>
     */
    int getErrCodeValue();
    /**
     * <code>.fsapi.ErrCode ErrCode = 2;</code>
     */
    fsapi.GlobalDef.ErrCode getErrCode();

    /**
     * <code>string ErrMsg = 3;</code>
     */
    java.lang.String getErrMsg();
    /**
     * <code>string ErrMsg = 3;</code>
     */
    com.google.protobuf.ByteString
        getErrMsgBytes();

    /**
     * <code>string ReqId = 4;</code>
     */
    java.lang.String getReqId();
    /**
     * <code>string ReqId = 4;</code>
     */
    com.google.protobuf.ByteString
        getReqIdBytes();
  }
  /**
   * Protobuf type {@code fsapi.ResHeader}
   */
  public  static final class ResHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:fsapi.ResHeader)
      ResHeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResHeader.newBuilder() to construct.
    private ResHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResHeader() {
      errCode_ = 0;
      errMsg_ = "";
      reqId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ResHeader();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              version_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              errCode_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              errMsg_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              reqId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fsapi.GlobalDef.internal_static_fsapi_ResHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fsapi.GlobalDef.internal_static_fsapi_ResHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fsapi.GlobalDef.ResHeader.class, fsapi.GlobalDef.ResHeader.Builder.class);
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <pre>
     * 现在版本默认为 1
     * </pre>
     *
     * <code>int32 Version = 1;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int ERRCODE_FIELD_NUMBER = 2;
    private int errCode_;
    /**
     * <code>.fsapi.ErrCode ErrCode = 2;</code>
     */
    public int getErrCodeValue() {
      return errCode_;
    }
    /**
     * <code>.fsapi.ErrCode ErrCode = 2;</code>
     */
    public fsapi.GlobalDef.ErrCode getErrCode() {
      @SuppressWarnings("deprecation")
      fsapi.GlobalDef.ErrCode result = fsapi.GlobalDef.ErrCode.valueOf(errCode_);
      return result == null ? fsapi.GlobalDef.ErrCode.UNRECOGNIZED : result;
    }

    public static final int ERRMSG_FIELD_NUMBER = 3;
    private volatile java.lang.Object errMsg_;
    /**
     * <code>string ErrMsg = 3;</code>
     */
    public java.lang.String getErrMsg() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errMsg_ = s;
        return s;
      }
    }
    /**
     * <code>string ErrMsg = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrMsgBytes() {
      java.lang.Object ref = errMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQID_FIELD_NUMBER = 4;
    private volatile java.lang.Object reqId_;
    /**
     * <code>string ReqId = 4;</code>
     */
    public java.lang.String getReqId() {
      java.lang.Object ref = reqId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reqId_ = s;
        return s;
      }
    }
    /**
     * <code>string ReqId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getReqIdBytes() {
      java.lang.Object ref = reqId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (version_ != 0) {
        output.writeInt32(1, version_);
      }
      if (errCode_ != fsapi.GlobalDef.ErrCode.ERR_SUCCESS.getNumber()) {
        output.writeEnum(2, errCode_);
      }
      if (!getErrMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errMsg_);
      }
      if (!getReqIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, reqId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (errCode_ != fsapi.GlobalDef.ErrCode.ERR_SUCCESS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, errCode_);
      }
      if (!getErrMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errMsg_);
      }
      if (!getReqIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, reqId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof fsapi.GlobalDef.ResHeader)) {
        return super.equals(obj);
      }
      fsapi.GlobalDef.ResHeader other = (fsapi.GlobalDef.ResHeader) obj;

      if (getVersion()
          != other.getVersion()) return false;
      if (errCode_ != other.errCode_) return false;
      if (!getErrMsg()
          .equals(other.getErrMsg())) return false;
      if (!getReqId()
          .equals(other.getReqId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + ERRCODE_FIELD_NUMBER;
      hash = (53 * hash) + errCode_;
      hash = (37 * hash) + ERRMSG_FIELD_NUMBER;
      hash = (53 * hash) + getErrMsg().hashCode();
      hash = (37 * hash) + REQID_FIELD_NUMBER;
      hash = (53 * hash) + getReqId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static fsapi.GlobalDef.ResHeader parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fsapi.GlobalDef.ResHeader parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fsapi.GlobalDef.ResHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fsapi.GlobalDef.ResHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fsapi.GlobalDef.ResHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fsapi.GlobalDef.ResHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fsapi.GlobalDef.ResHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fsapi.GlobalDef.ResHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static fsapi.GlobalDef.ResHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static fsapi.GlobalDef.ResHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static fsapi.GlobalDef.ResHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static fsapi.GlobalDef.ResHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fsapi.GlobalDef.ResHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fsapi.ResHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fsapi.ResHeader)
        fsapi.GlobalDef.ResHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fsapi.GlobalDef.internal_static_fsapi_ResHeader_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fsapi.GlobalDef.internal_static_fsapi_ResHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fsapi.GlobalDef.ResHeader.class, fsapi.GlobalDef.ResHeader.Builder.class);
      }

      // Construct using fsapi.GlobalDef.ResHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        version_ = 0;

        errCode_ = 0;

        errMsg_ = "";

        reqId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fsapi.GlobalDef.internal_static_fsapi_ResHeader_descriptor;
      }

      @java.lang.Override
      public fsapi.GlobalDef.ResHeader getDefaultInstanceForType() {
        return fsapi.GlobalDef.ResHeader.getDefaultInstance();
      }

      @java.lang.Override
      public fsapi.GlobalDef.ResHeader build() {
        fsapi.GlobalDef.ResHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public fsapi.GlobalDef.ResHeader buildPartial() {
        fsapi.GlobalDef.ResHeader result = new fsapi.GlobalDef.ResHeader(this);
        result.version_ = version_;
        result.errCode_ = errCode_;
        result.errMsg_ = errMsg_;
        result.reqId_ = reqId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fsapi.GlobalDef.ResHeader) {
          return mergeFrom((fsapi.GlobalDef.ResHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fsapi.GlobalDef.ResHeader other) {
        if (other == fsapi.GlobalDef.ResHeader.getDefaultInstance()) return this;
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (other.errCode_ != 0) {
          setErrCodeValue(other.getErrCodeValue());
        }
        if (!other.getErrMsg().isEmpty()) {
          errMsg_ = other.errMsg_;
          onChanged();
        }
        if (!other.getReqId().isEmpty()) {
          reqId_ = other.reqId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fsapi.GlobalDef.ResHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fsapi.GlobalDef.ResHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int version_ ;
      /**
       * <pre>
       * 现在版本默认为 1
       * </pre>
       *
       * <code>int32 Version = 1;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <pre>
       * 现在版本默认为 1
       * </pre>
       *
       * <code>int32 Version = 1;</code>
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 现在版本默认为 1
       * </pre>
       *
       * <code>int32 Version = 1;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private int errCode_ = 0;
      /**
       * <code>.fsapi.ErrCode ErrCode = 2;</code>
       */
      public int getErrCodeValue() {
        return errCode_;
      }
      /**
       * <code>.fsapi.ErrCode ErrCode = 2;</code>
       */
      public Builder setErrCodeValue(int value) {
        errCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.fsapi.ErrCode ErrCode = 2;</code>
       */
      public fsapi.GlobalDef.ErrCode getErrCode() {
        @SuppressWarnings("deprecation")
        fsapi.GlobalDef.ErrCode result = fsapi.GlobalDef.ErrCode.valueOf(errCode_);
        return result == null ? fsapi.GlobalDef.ErrCode.UNRECOGNIZED : result;
      }
      /**
       * <code>.fsapi.ErrCode ErrCode = 2;</code>
       */
      public Builder setErrCode(fsapi.GlobalDef.ErrCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        errCode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.fsapi.ErrCode ErrCode = 2;</code>
       */
      public Builder clearErrCode() {
        
        errCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errMsg_ = "";
      /**
       * <code>string ErrMsg = 3;</code>
       */
      public java.lang.String getErrMsg() {
        java.lang.Object ref = errMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errMsg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ErrMsg = 3;</code>
       */
      public com.google.protobuf.ByteString
          getErrMsgBytes() {
        java.lang.Object ref = errMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ErrMsg = 3;</code>
       */
      public Builder setErrMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ErrMsg = 3;</code>
       */
      public Builder clearErrMsg() {
        
        errMsg_ = getDefaultInstance().getErrMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string ErrMsg = 3;</code>
       */
      public Builder setErrMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errMsg_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object reqId_ = "";
      /**
       * <code>string ReqId = 4;</code>
       */
      public java.lang.String getReqId() {
        java.lang.Object ref = reqId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reqId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ReqId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getReqIdBytes() {
        java.lang.Object ref = reqId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reqId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ReqId = 4;</code>
       */
      public Builder setReqId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ReqId = 4;</code>
       */
      public Builder clearReqId() {
        
        reqId_ = getDefaultInstance().getReqId();
        onChanged();
        return this;
      }
      /**
       * <code>string ReqId = 4;</code>
       */
      public Builder setReqIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reqId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:fsapi.ResHeader)
    }

    // @@protoc_insertion_point(class_scope:fsapi.ResHeader)
    private static final fsapi.GlobalDef.ResHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new fsapi.GlobalDef.ResHeader();
    }

    public static fsapi.GlobalDef.ResHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResHeader>
        PARSER = new com.google.protobuf.AbstractParser<ResHeader>() {
      @java.lang.Override
      public ResHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResHeader> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public fsapi.GlobalDef.ResHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fsapi_ReqHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fsapi_ReqHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fsapi_ResHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fsapi_ResHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020global_def.proto\022\005fsapi\"7\n\tReqHeader\022\017" +
      "\n\007Version\030\001 \001(\005\022\r\n\005DevId\030\002 \001(\t\022\n\n\002Ts\030\003 \001" +
      "(\r\"\\\n\tResHeader\022\017\n\007Version\030\001 \001(\005\022\037\n\007ErrC" +
      "ode\030\002 \001(\0162\016.fsapi.ErrCode\022\016\n\006ErrMsg\030\003 \001(" +
      "\t\022\r\n\005ReqId\030\004 \001(\t*a\n\007ErrCode\022\017\n\013ERR_SUCCE" +
      "SS\020\000\022\016\n\nERR_FAILED\020\001\022\027\n\023ERR_DEVID_NOT_EX" +
      "IST\020\002\022\034\n\030ERR_CONN_TO_DA_NOT_READY\020\003B3Z1g" +
      "ithub.com/iopig/feed-scale/interface/grp" +
      "c/go_outb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_fsapi_ReqHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_fsapi_ReqHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fsapi_ReqHeader_descriptor,
        new java.lang.String[] { "Version", "DevId", "Ts", });
    internal_static_fsapi_ResHeader_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_fsapi_ResHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fsapi_ResHeader_descriptor,
        new java.lang.String[] { "Version", "ErrCode", "ErrMsg", "ReqId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
